[package]
name = "lumos_1"
version = "0.1.0"
authors = ["Abhinav Sharma <abhi18av@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "lumos_1"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
